import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import roomsRouter from "./rooms";
import tablesRouter from "./tables";
import departmentsRouter from "./departments";
import printersRouter from "./printers";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import dashboardRouter from "./dashboard";
import settingsRouter from "./settings";
import authRouter from "./auth";
import customersRouter from "./customers";
import invoicesRouter from "./invoices";
import fiscalRouter from "./fiscal";
import discountsRouter from "./discounts";
import promotionsRouter from "./promotions";
import couriersRouter from "./couriers";
import combosRouter from "./combos";
import happyHourRouter from "./happy-hour";
import kpCommentsRouter from "./kp-comments";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/categories", categoriesRouter);
router.use("/products", productsRouter);
router.use("/rooms", roomsRouter);
router.use("/tables", tablesRouter);
router.use("/departments", departmentsRouter);
router.use("/printers", printersRouter);
router.use("/orders", ordersRouter);
router.use("/payments", paymentsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/settings", settingsRouter);
router.use("/auth", authRouter);
router.use("/customers", customersRouter);
router.use("/invoices", invoicesRouter);
router.use("/fiscal", fiscalRouter);
router.use("/discounts", discountsRouter);
router.use("/promotions", promotionsRouter);
router.use("/couriers", couriersRouter);
router.use("/combos", combosRouter);
router.use("/happy-hour", happyHourRouter);
router.use("/kp-comments", kpCommentsRouter);

export default router;
